esp = [];
espe = [];
esperimento = [];
odorsRearranged = [4     6     7     9    10     1     2     3     5     8];
for idxExp =  1:length(coaAA.esp)
    for idxShank = 1:4
        if ~isempty(coaAA.esp(idxExp).shank(idxShank).SUA)
            for idxUnit = 1:length(coaAA.esp(idxExp).shank(idxShank).SUA.cell)
                    idxO = 0;
                    for idxOdor = odorsRearranged
                        idxO = idxO + 1;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).peakLatency =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).peakLatency;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).halfWidth =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).halfWidth;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).onsetLatency =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).onsetLatency;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).AnalogicResponse300ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).AnalogicResponse300ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).AnalogicBsl300ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).AnalogicBsl300ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).auROC300ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).auROC300ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).digitalResponse300ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).digitalResponse300ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).AnalogicResponse1000ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).AnalogicResponse1000ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).AnalogicBsl1000ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).AnalogicBsl1000ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).auROC1000ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).auROC1000ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).digitalResponse1000ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).digitalResponse1000ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).AnalogicResponse2000ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).AnalogicResponse2000ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).AnalogicBsl2000ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).AnalogicBsl2000ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).auROC2000ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).auROC2000ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).digitalResponse2000ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).digitalResponse2000ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).AnalogicResponseOffset =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).AnalogicResponseOffset;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).AnalogicBslOffset =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).AnalogicBslOffset;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).auROCOffset =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).auROCOffset;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).trialExc1000ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialExc1000ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).trialInh1000ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialInh1000ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).trialExcPeak1000ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialExcPeak1000ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).trialInhPeak1000ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialInhPeak1000ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).trialExcWind1000ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialExcWind1000ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).trialInhWind1000ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialInhWind1000ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).trialExcPeakDelta1000ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialExcPeakDelta1000ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).trialInhPeakDelta1000ms =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialInhPeakDelta1000ms;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).AnalogicResponseDeltaPeakHz =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).AnalogicResponseDeltaPeakHz;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).DigitalResponseDeltaPeak =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).DigitalResponseDeltaPeak;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).responsePeakFractionExc =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).responsePeakFractionExc;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).responsePeakFractionInh =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).responsePeakFractionInh;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).responseWindFractionExc =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).responseWindFractionExc;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).responseWindFractionInh =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).responseWindFractionInh;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).trialExc1000msBs =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialExc1000msBs;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).trialInh1000msBs =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialInh1000msBs;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).trialExcPeak1000msBs =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialExcPeak1000msBs;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).trialInhPeak1000msBs =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialInhPeak1000msBs;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).trialExcWind1000msBs =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialExcWind1000msBs;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).trialInhWind1000msBs =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialInhWind1000msBs;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).trialExcPeakDelta1000msBs =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialExcPeakDelta1000msBs;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).trialInhPeakDelta1000msBs =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialInhPeakDelta1000msBs;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).responsePeakFractionExcBs =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).responsePeakFractionExcBs;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).responsePeakFractionInhBs =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).responsePeakFractionInhBs;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).responseWindFractionExcBs =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).responseWindFractionExcBs;
                        esp(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).responseWindFractionInhBs =...
                            coaAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).responseWindFractionInhBs;
                        
                        espe(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).spikeMatrix =...
                            coaAA_1.espe(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).spikeMatrix;
                        
                        esperimento(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).spikeMatrixRad =...
                            coaAA_3.esperimento(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).spikeMatrixRad;
                        esperimento(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).sniffBinnedPsth =...
                            coaAA_3.esperimento(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).sniffBinnedPsth;
                        esperimento(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).ina_exc_cycleLength =...
                            coaAA_3.esperimento(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).ina_exc_cycleLength;
                        esperimento(idxExp).shank(idxShank).SUA.cell(idxUnit).odor(idxO).alphaTrial =...
                            coaAA_3.esperimento(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).alphaTrial;
                    end
            end
        end
    end
end
save('plCoA_AA_1.mat', 'esp')
save('plCoA_AA_2.mat', 'espe')
save('plCoA_AA_3.mat', 'esperimento')
esp = [];
espe = [];
esperimento = [];


odorsRearranged = [4     6     7     9    10     1     2     3     5     8];
for idxExp =  1:length(pcxAA.esp)
    for idxShank = 1:4
        if ~isempty(pcxAA.esp(idxExp).shank(idxShank).SUA)
            for idxUnit = 1:length(pcxAA.esp(idxExp).shank(idxShank).SUA.cell)
                    idxO = 0;
                    for idxOdor = odorsRearranged
                        idxO = idxO + 1;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).peakLatency =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).peakLatency;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).halfWidth =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).halfWidth;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).onsetLatency =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).onsetLatency;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).AnalogicResponse300ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).AnalogicResponse300ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).AnalogicBsl300ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).AnalogicBsl300ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).auROC300ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).auROC300ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).digitalResponse300ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).digitalResponse300ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).AnalogicResponse1000ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).AnalogicResponse1000ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).AnalogicBsl1000ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).AnalogicBsl1000ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).auROC1000ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).auROC1000ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).digitalResponse1000ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).digitalResponse1000ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).AnalogicResponse2000ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).AnalogicResponse2000ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).AnalogicBsl2000ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).AnalogicBsl2000ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).auROC2000ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).auROC2000ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).digitalResponse2000ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).digitalResponse2000ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).AnalogicResponseOffset =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).AnalogicResponseOffset;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).AnalogicBslOffset =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).AnalogicBslOffset;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).auROCOffset =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).auROCOffset;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).trialExc1000ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialExc1000ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).trialInh1000ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialInh1000ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).trialExcPeak1000ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialExcPeak1000ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).trialInhPeak1000ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialInhPeak1000ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).trialExcWind1000ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialExcWind1000ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).trialInhWind1000ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialInhWind1000ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).trialExcPeakDelta1000ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialExcPeakDelta1000ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).trialInhPeakDelta1000ms =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialInhPeakDelta1000ms;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).AnalogicResponseDeltaPeakHz =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).AnalogicResponseDeltaPeakHz;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).DigitalResponseDeltaPeak =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).DigitalResponseDeltaPeak;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).responsePeakFractionExc =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).responsePeakFractionExc;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).responsePeakFractionInh =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).responsePeakFractionInh;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).responseWindFractionExc =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).responseWindFractionExc;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).responseWindFractionInh =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).responseWindFractionInh;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).trialExc1000msBs =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialExc1000msBs;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).trialInh1000msBs =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialInh1000msBs;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).trialExcPeak1000msBs =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialExcPeak1000msBs;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).trialInhPeak1000msBs =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialInhPeak1000msBs;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).trialExcWind1000msBs =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialExcWind1000msBs;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).trialInhWind1000msBs =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialInhWind1000msBs;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).trialExcPeakDelta1000msBs =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialExcPeakDelta1000msBs;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).trialInhPeakDelta1000msBs =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).trialInhPeakDelta1000msBs;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).responsePeakFractionExcBs =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).responsePeakFractionExcBs;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).responsePeakFractionInhBs =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).responsePeakFractionInhBs;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).responseWindFractionExcBs =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).responseWindFractionExcBs;
                        esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).responseWindFractionInhBs =...
                            pcxAA.esp(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).responseWindFractionInhBs;
                        
                        espe(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).spikeMatrix =...
                            pcxAA_1.espe(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).spikeMatrix;
                        
                        esperimento(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).spikeMatrixRad =...
                            pcxAA_3.esperimento(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).spikeMatrixRad;
                        esperimento(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).sniffBinnedPsth =...
                            pcxAA_3.esperimento(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).sniffBinnedPsth;
                        esperimento(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).ina_exc_cycleLength =...
                            pcxAA_3.esperimento(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).ina_exc_cycleLength;
                        esperimento(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxO).alphaTrial =...
                            pcxAA_3.esperimento(idxExp).idxShank(idxShank).SUA.cell(idxUnit).odor(idxOdor).alphaTrial;
                    end
            end
        end
    end
end

save('aPCx_AA_1.mat', 'esp')
save('aPCx_AA_2.mat', 'espe')
save('aPCx_AA_3.mat', 'esperimento')
